# 인덱싱(Indexing)   
   
Python list / Numpy Array의 인덱싱 방법과 비슷함   
   
0부터 시작, 마지막 인덱스는 -1로 접근   
   
인덱스에 해당하는 범위를 지정하여 여러개의 요소를 슬라이싱 추출하는 것도 가능

In [1]:
import tensorflow as tf

In [17]:
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

# 0번째 요소의 스칼라 값 출력
print("0th : ", tf.get_static_value(vec[0]))
# 마지막 요소의 스칼라 값 출력
print("last scalar value : ", tf.get_static_value(vec[-1]))
# 0~2 번째까지의 해당하는 요소 값들을 모두 출력
print("0~2 : ", tf.get_static_value(vec[0:3]))
print("0~2 : ", tf.get_static_value(vec[:3]))

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
0th :  10
last scalar value :  50
0~2 :  [10 20 30]
0~2 :  [10 20 30]


In [25]:
# 2차원 행렬 인덱싱
# 행방향, 열방향 인덱스를 지정하는 방식

matrix = tf.constant([[1,2,3,4],
                     [5,6,7,8]])
print(matrix)
print(tf.rank(matrix))
print('-----------------')

# [0행, 2열]
print(tf.get_static_value(matrix[0,2]))
# [1행, 1열]
print(tf.get_static_value(matrix[1,1]))
# [0행, 모든열]
print(tf.get_static_value(matrix[0,:]))
# [모든 행, 1열]
print(tf.get_static_value(matrix[:,1]))
# [모든 행, 모든 열]
print(tf.get_static_value(matrix[:,:]))

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
-----------------
3
6
[1 2 3 4]
[2 6]
[[1 2 3 4]
 [5 6 7 8]]


In [31]:
# 랭크 3 텐서 (고차원 텐서)
# 2차원 텐서의 접근을 확장한 느낌

tensor = tf.constant([
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],

    [[13,14,15,16],
     [17,18,19,20],
     [21,22,23,24]],

    [[25,26,27,28],
     [29,30,31,32],
     [33,34,35,36]]
    ])

# 0번째 덩어리의 모든 행, 모든 열
print(tf.get_static_value(tensor[0,:,:]))
print('---')
# 1번째 덩어리의 1번째 행, 2번째 열
print(tf.get_static_value(tensor[1,1,2]))
print('---')
# 1번째 덩어리의 1번째 행까지, 2번째 열까지
print(tf.get_static_value(tensor[1,:2,:3]))
print('---')
# 0~1 번째의 덩어리에서 2번째 행까지, 2~3째 열까지
print(tf.get_static_value(tensor[:2,:3,2:4]))
print('---')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---
19
---
[[13 14 15]
 [17 18 19]]
---
[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]
---


# 형태 변환 (tf.reshape)   
   
Numpy의 reshape와 상당 부분 유사함   


In [32]:
tensor = tf.constant(range(1,25))
print(tensor)
# 요소가 24개 들어가있는 벡터

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


In [33]:
# 백터를 행렬 형태로 변환

tensor1 = tf.reshape(tensor, [4,6]) # 변환 전과 변환 후 요소의 갯수는 동일해야함
print(tensor1)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]], shape=(4, 6), dtype=int32)


In [36]:
# (3,6) 형태로 변환
# 행 인덱스에 -1 이 있는 경우 => 몇개여도 상관없다는 선언 /
# 다른 파라미터 갯수는 명시해야함( 행 -1이면 열은 고정값, 열 -1 이면 행은 고정값 요런식)

# tensor2 = tf.reshape(tensor1, [3,8])
tensor2 = tf.reshape(tensor1, [-1,8])
print(tensor2)

tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int32)


In [37]:
# (3,8) => (24,) 형태로 다시 변환

# tensor3 = tf.reshape(tensor2, [24])
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)


# 변수 (tf.Variable)   
   
Tensorflow : 계산처리 [그래프] 라는 객체를 구축 후, 그 그래프를 실행하는 것   
   
변수 : 텐서플로우를 활용해서 딥러닝 모델을 만들고, 학습을 시킬 때 정교한 연산을 제어하기 위해서 사용   
변수는 변화하는 학습을 저장하기 위한 그룹

In [39]:
tensor = tf.constant([[10,20,30],
                     [40,50,60]])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [40]:
# tensor를 Variable 함수에 입력 => tensorflow의 변수가 하나 생성

var1  = tf.Variable(tensor)
print(var1)

# 변수를 업데이트하면 초기값은 다른 값으로 변경될 수 있음

# tf.constant() : 상수값으로 지정하기 위한 함수, 한번 지정하면 값 변경 불가
# tf.Variable() : 변수, 텐서 구조에 저장되어 있는 값이 변경될 수 있음

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>


In [41]:
# assign() 함수 : tensorflow 변수에 새로운 데이터를 할당하는 함수
var1.assign([[100,200,300],
             [400,500,600]])
print(var1)

# 주의 : 새로 입력하고자 하는 배열의 크기, 자료값이 원래 변수값의 형식(배열 크기, 자료형)과 동일해야함

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500, 600]], dtype=int32)>


In [42]:
# tf.convert_to_tensor() : tensorflow 변수를 tensor로 변환
# tensor로 상수화 하고 나면 텐서의 크기, 저장하고 있는 값 변경이 불가능함 => ㄹㅇ 상수화

tensor1 = tf.convert_to_tensor(var1)
print(tensor1)

tf.Tensor(
[[100 200 300]
 [400 500 600]], shape=(2, 3), dtype=int32)


In [43]:
# 연산자 사용도 가능함
var1 + tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 200,  400,  600],
       [ 800, 1000, 1200]], dtype=int32)>

In [44]:
tf.__version__

'2.17.0'

In [47]:
import tensorflow.compat.v1 as tf # tensorflow 1버전 사용
tf.compat.v1.disable_eager_execution() # 즉시 실행 모드 비활성화

a1 = tf.constant(10)
b1 = tf.constant(20)
c1 = tf.constant(30)
r = a1 + b1 + c1

# 변수 정의하기
v = tf.Variable(0)
assign = tf.assign(v,r)

# 데이터 플로우 그래프 정의하기 (데이터의 흐름을 연산하여 결과 값을 도출하는 모델)

# Session
sess = tf.Session()
sess.run(assign)
print(sess.run(v))

60


# 플레이스 홀더(Placeholder)   
   
딥러닝을 할 때 데이터 학습이 반드시 필요함   
이 학습을 진행할 때 학습할 데이터를 꼭! 입력을 해줘야함   
데이터를 입력받기 위해서 필요한 비어있는 변수

In [ ]:
# placeholder 의 파라미터
# 실행은 ㄴㄴ

placeholer(
    dtype,        # 자료형, 반드시 적어야함
    shape = None, # 입력 데이터의 형태 (상수값 or 배열 정보)
    name = None   # 이름 - 굳이 설정 안해도 상관없음
)

In [ ]:
tf.disable_v2_behavior() # v2 사용 안함

ph1 = tf.placeholder(dtype = tf.float32)
ph2 = tf.placeholder(dtype = tf.float32)
ph3 = tf.placeholder(dtype = tf.float32)

rr = ph1 + ph2 + ph3

sess = tf.Session()
print(sess.run(rr, feed_dict={ph1 : 10, ph2 : 20, ph3 : 30}))
sess.close()

# placeholder는 다른 tensor를 할당할 때 사용함 => tensor 매핑시 사용
# 할당을 위해서 사용하는 것 : feed_dict

# tf.Variable vs tf.placeholder   
   
- tf.Variable : 데이터의 상태를 저장하기 위해 사용
- tf.placeholder : 데이터를 입력하기 위해 사용