# Numpy 함수   
# 하나의 array에 적용(단항 유니버셜 함수)
유니버셜 함수 :   
ndarray 안에 있는 데이터의 요소별로 연산을 수행해주는 함수   
  

In [2]:
import numpy as np

ar1 = np.random.randn(5,3)
ar1

array([[ 1.49960383,  0.58142138,  0.62173976],
       [-0.21986568,  0.55160364, -1.60774603],
       [ 1.12101572, -0.59276528,  0.85244033],
       [ 1.21237419, -0.09428523,  0.80965799],
       [-2.20013885,  0.90218723,  0.06787363]])

In [3]:
# 각 요소들의 절대값
np.abs(ar1)

array([[1.49960383, 0.58142138, 0.62173976],
       [0.21986568, 0.55160364, 1.60774603],
       [1.12101572, 0.59276528, 0.85244033],
       [1.21237419, 0.09428523, 0.80965799],
       [2.20013885, 0.90218723, 0.06787363]])

In [4]:
# 각 요소들의 제곱근
np.sqrt(ar1)

<ipython-input-4-04d6e9f35fde>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[1.22458313, 0.76250992, 0.78850476],
       [       nan, 0.74270024,        nan],
       [1.0587803 ,        nan, 0.92327695],
       [1.10107865,        nan, 0.89980997],
       [       nan, 0.94983537, 0.26052569]])

In [5]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[2.24881165e+00, 3.38050826e-01, 3.86560326e-01],
       [4.83409171e-02, 3.04266579e-01, 2.58484731e+00],
       [1.25667625e+00, 3.51370672e-01, 7.26654510e-01],
       [1.46985118e+00, 8.88970422e-03, 6.55546056e-01],
       [4.84061094e+00, 8.13941795e-01, 4.60683027e-03]])

In [ ]:
# 각 로그를 자연로그, 상용로그, 밑이 2인 로그를 씌운 값 계산
#자연 로그
print(np.log(ar1))
print()
#상용 로그
print(np.log10(ar1))
print()
#밑이 2인 로그
print(np.log2(ar1))


In [6]:
# 각 요소의 부호 나타내기 ( + : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[ 1.,  1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.]])

In [10]:
# 각 요소의 올림 / 내림 / 반올림
r = np.ceil(ar1)
r1 = np.floor(ar1)
r2 = np.round(ar1)
print(r)
print(r1)
print(r2)

[[ 2.  1.  1.]
 [-0.  1. -1.]
 [ 2. -0.  1.]
 [ 2. -0.  1.]
 [-2.  1.  1.]]
[[ 1.  0.  0.]
 [-1.  0. -2.]
 [ 1. -1.  0.]
 [ 1. -1.  0.]
 [-3.  0.  0.]]
[[ 1.  1.  1.]
 [-0.  1. -2.]
 [ 1. -1.  1.]
 [ 1. -0.  1.]
 [-2.  1.  0.]]


In [11]:
# 각 요소가 nan인 경우 True, 아니면 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False
np.isinf(ar1)

In [12]:
# 각 요소에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)
# -h : 쌍곡선 함수
np.cos(ar1)

array([[ 0.07113237,  0.83568285,  0.81286637],
       [ 0.97592675,  0.85168522, -0.0369413 ],
       [ 0.43476797,  0.82939901,  0.65814781],
       [ 0.35079708,  0.99555844,  0.68974611],
       [-0.58861337,  0.61989517,  0.99769747]])

# 두 개의 array에 적용 가능한 함수 ( 이항 유니버셜 함수 )

In [13]:
ar2 = np.random.randn(5,3)
ar2

array([[ 0.28618248,  0.53449311, -1.5304062 ],
       [-0.57954254, -0.12731834,  0.14816401],
       [ 0.82970276, -1.36824187, -0.23038209],
       [ 1.35066421, -0.65135121, -0.67719015],
       [-0.37021725, -0.68699523,  0.27264874]])

In [14]:
# 두 개의 array에 대해 동일한 위치 요소끼리 연산
# 계산함수(add, substract, multiply, divide)

np.multiply(ar1, ar2)

array([[ 0.42916035,  0.31076572, -0.95151438],
       [ 0.12742151, -0.07022926, -0.23821009],
       [ 0.93010984,  0.81104627, -0.19638698],
       [ 1.63751043,  0.0614128 , -0.54829242],
       [ 0.81452936, -0.61979832,  0.01850566]])

In [15]:
# 두 개의 array에 대해 동일한 위치 요소끼리 비교해서 최대값 or 최소값 계산
# maximum, minimum
np.maximum(ar1, ar2)

array([[ 1.49960383,  0.58142138,  0.62173976],
       [-0.21986568,  0.55160364,  0.14816401],
       [ 1.12101572, -0.59276528,  0.85244033],
       [ 1.35066421, -0.09428523,  0.80965799],
       [-0.37021725,  0.90218723,  0.27264874]])

# 통계 함수   
통계 함수를 통해서 array의 합이나 평균들을 구할 때   
추가로 axis 라는 파라미터에 대한 값을 지정해서   
열 또는 행의 합, 평균, 외 기타 등등에 대한 값을 구할 수 있음

In [16]:
# 열 간의 합을 계산
# Numpy에서 axis = 0 은 열을 의미함
# axis = 1 은 행을 의미함
np.sum(ar1, axis=0)

array([1.41298922, 1.34816175, 0.74396567])

In [18]:
np.sum(ar1, axis=1)

array([ 2.70276497, -1.27600807,  1.38069078,  1.92774695, -1.23007798])

In [ ]:
# 전체 요소의 평균 계산
np.min(ar1, axis=0)

In [19]:
# 전체 요소의 표준 편차, 분산, 최소값, 최대값
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어져있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 있는지를 나타내는 지표
# std, var, min, max
np.std(ar1)

1.0073056261494164

In [25]:
# 전체 요소 중 최소값, 최대값이 위치한 인덱스 반환
# argmin, argmax
print(ar1)
np.argmin(ar1)

[[ 1.49960383  0.58142138  0.62173976]
 [-0.21986568  0.55160364 -1.60774603]
 [ 1.12101572 -0.59276528  0.85244033]
 [ 1.21237419 -0.09428523  0.80965799]
 [-2.20013885  0.90218723  0.06787363]]


12

In [21]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, cumprod)
np.cumsum(ar1)

array([1.49960383, 2.08102522, 2.70276497, 2.48289929, 3.03450294,
       1.4267569 , 2.54777263, 1.95500735, 2.80744768, 4.01982187,
       3.92553664, 4.73519463, 2.53505578, 3.43724301, 3.50511665])

In [27]:
# 사분위수
# 데이터를 4등분 했을 때 0%, 25%, 50%, 100% 에 해당하는 값들
np.quantile(ar1, [0, 0.25, 0.5, 0.75])

array([-2.20013885, -0.15707545,  0.58142138,  0.87731378])

# 기타 함수

In [28]:
# 전체 요소에 대해 오름차순 정렬
np.sort(ar1)

array([[ 0.58142138,  0.62173976,  1.49960383],
       [-1.60774603, -0.21986568,  0.55160364],
       [-0.59276528,  0.85244033,  1.12101572],
       [-0.09428523,  0.80965799,  1.21237419],
       [-2.20013885,  0.06787363,  0.90218723]])

In [29]:
# 행 / 열 방향 지정해서 정렬

# 열 방향으로 정렬
np.sort(ar1, axis=0)

array([[-2.20013885, -0.59276528, -1.60774603],
       [-0.21986568, -0.09428523,  0.06787363],
       [ 1.12101572,  0.55160364,  0.62173976],
       [ 1.21237419,  0.58142138,  0.80965799],
       [ 1.49960383,  0.90218723,  0.85244033]])

In [30]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
number = [1,2,3]
letters = ['A', 'B', 'C']
for pair in zip(number, letters):
    print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
